### ISSUE TITLE
Response objects are not immutable in miniflare

### ISSUE THREAD

**Issue by Immortalin** [cloudflare/miniflare#243] opened 2022-04-13 22:46 UTC
Response objects are not immutable in miniflare, headers can be set while an opaque error will be generated in production deployments. 

## Replication
Run this repo in miniflare
https://github.com/Immortalin/vite-plugin-ssr-cloudflare-pages-demo

There is no error in development, however, in production the worker will return the usual 1101 exception.

Commenting out the headers code [here](https://github.com/Immortalin/vite-plugin-ssr-cloudflare-pages-demo/blob/be2594d5e9185f9b709db356396c4aad4586117f/worker/worker.ts#L23) solves the problem.
![image](https://user-images.githubusercontent.com/7126128/163282089-6b4bcb32-6d4a-479f-a183-5ff8a0997255.png)

**Comment by GregBrimble** [comment] 2022-04-30 23:39
Dupe of #242

**Closed** 2022-05-20 21:55 UTC
